apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_CLIENTS: cG9zdGdyZXM=  # Base64 de 'postgres'
  DB_PASSWORD_CLIENTS: ZmVsaXBlYjIyMg==  # Base64 de 'felipeb222'